/* Generates the PWA shell's colour-bearing files from tokens.json.
 *
 * A manifest and a <meta name="theme-color"> cannot hold var(--ds-*) — they
 * need literal hex. Deriving those literals here instead of hand-copying them
 * means an upstream token sync updates the app chrome too, rather than quietly
 * leaving the status bar the old colour.
 *
 * Zero dependencies, same as the other scripts in this directory.
 *
 * Run after extract-tokens.mjs:  node design-system/scripts/build-pwa.mjs
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";

const DIR = new URL("../", import.meta.url).pathname;
const { tokens, source } = JSON.parse(
  readFileSync(`${DIR}tokens/tokens.json`, "utf8"),
);

/* ── oklch() → sRGB hex ────────────────────────────────────────────────────
 * OKLCH → OKLab → linear sRGB → gamma-encoded sRGB, per CSS Color 4.
 * Matrices are the standard Björn Ottosson coefficients.
 */
function parseOklch(value) {
  const m = /^oklch\(\s*([\d.]+%?)\s+([\d.]+%?)\s+([\d.]+)(?:\s*\/\s*([\d.]+%?))?\s*\)$/.exec(
    value.trim(),
  );
  if (!m) return null;
  const num = (s, pctScale) =>
    s.endsWith("%") ? parseFloat(s) / 100 * pctScale : parseFloat(s);
  return {
    L: num(m[1], 1),
    C: num(m[2], 1),
    H: parseFloat(m[3]),
    alpha: m[4] === undefined ? 1 : num(m[4], 1),
  };
}

function oklchToRgb({ L, C, H }) {
  const h = (H * Math.PI) / 180;
  const a = C * Math.cos(h);
  const b = C * Math.sin(h);

  const l_ = L + 0.3963377774 * a + 0.2158037573 * b;
  const m_ = L - 0.1055613458 * a - 0.0638541728 * b;
  const s_ = L - 0.0894841775 * a - 1.291485548 * b;

  const l = l_ ** 3;
  const m = m_ ** 3;
  const s = s_ ** 3;

  const lin = [
    4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s,
    -1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s,
    -0.0041960863 * l - 0.7034186147 * m + 1.707614701 * s,
  ];

  // Gamut-clip by clamping each channel, matching what browsers do for these
  // in-gamut greys and near-primaries. None of the tokens used here are wide.
  return lin.map((v) => {
    const enc = v <= 0.0031308 ? 12.92 * v : 1.055 * v ** (1 / 2.4) - 0.055;
    return Math.max(0, Math.min(255, Math.round(enc * 255)));
  });
}

const hex = (value) => {
  const parsed = parseOklch(value);
  if (!parsed) throw new Error(`cannot parse colour: ${value}`);
  if (parsed.alpha !== 1) throw new Error(`alpha colour has no hex form: ${value}`);
  return `#${oklchToRgb(parsed).map((c) => c.toString(16).padStart(2, "0")).join("")}`;
};

/* ── The colours a PWA shell actually needs ───────────────────────────────── */
const WANTED = [
  "--ds-background-100", // theme_color + background_color, both themes
  "--ds-background-200",
  "--ds-gray-1000", // icon foreground
  "--ds-blue-700", // accent
];

const colors = {};
for (const name of WANTED) {
  const t = tokens[name];
  if (!t) throw new Error(`missing token ${name}`);
  colors[name] = { light: hex(t.light), dark: hex(t.dark) };
}

mkdirSync(`${DIR}pwa/icons`, { recursive: true });

writeFileSync(
  `${DIR}pwa/colors.json`,
  `${JSON.stringify(
    {
      note: "sRGB hex for the --ds-* tokens the PWA shell needs as literals (manifest, theme-color, icons). Generated by scripts/build-pwa.mjs — do not edit by hand.",
      source: `${source.package}@${source.version}`,
      colors,
    },
    null,
    2,
  )}\n`,
);

const themeLight = colors["--ds-background-100"].light;
const themeDark = colors["--ds-background-100"].dark;

/* ── manifest.webmanifest ─────────────────────────────────────────────────── */
writeFileSync(
  `${DIR}pwa/manifest.webmanifest`,
  `${JSON.stringify(
    {
      name: "V15C",
      short_name: "V15C",
      description: "V15C",
      start_url: "/",
      scope: "/",
      display: "standalone",
      orientation: "any",
      // Splash screen + app chrome. Both are --ds-background-100; a manifest
      // has one theme_color, so it carries the light value and theme.js
      // overrides the live <meta> when .dark is active.
      background_color: themeLight,
      theme_color: themeLight,
      icons: [
        { src: "/design-system/pwa/icons/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
        { src: "/design-system/pwa/icons/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
        { src: "/design-system/pwa/icons/icon-maskable-512.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
      ],
    },
    null,
    2,
  )}\n`,
);

/* ── head.html : copy-paste snippet ─────────────────────────────────────────
 * no-flash.js is embedded rather than linked — see the comment it carries.
 * Its block comments are stripped on the way in; the explanation belongs in the
 * source file, not in the <head> of every page. */
const inlineNoFlash = readFileSync(`${DIR}pwa/no-flash.js`, "utf8")
  .replace(/\/\*[\s\S]*?\*\//g, "")
  .split("\n")
  .map((l) => l.trimEnd())
  .join("\n")
  .replace(/\n{3,}/g, "\n\n")
  // A stripped comment can leave a block empty but for a blank line.
  .replace(/\n\s*\n(\s*\})/g, "\n$1")
  .trim()
  .split("\n")
  .map((l) => (l ? `  ${l}` : l))
  .join("\n");

writeFileSync(
  `${DIR}pwa/head.html`,
  `<!-- Geist PWA shell — paste into <head>, in this order.
     Generated by design-system/scripts/build-pwa.mjs — do not edit by hand.
     Paths assume the design system is served from /design-system/. -->

<!-- viewport-fit=cover is what makes env(safe-area-inset-*) non-zero. Without
     it the safe-area utilities in pwa.css resolve to 0 and notches clip. -->
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />

<!-- Status bar / titlebar. Literals are --ds-background-100; theme.js keeps the
     active one in sync when the .dark class is toggled by hand. -->
<meta name="theme-color" content="${themeLight}" media="(prefers-color-scheme: light)" />
<meta name="theme-color" content="${themeDark}" media="(prefers-color-scheme: dark)" />

<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />

<!-- MUST stay inline, and MUST run before first paint, or a home-screen launch
     renders one light frame before flipping to dark. An external <script src>
     is fetched too late even when render-blocking — keep this in the HTML. -->
<script>
${inlineNoFlash}
</script>

<!-- Preloaded ahead of the stylesheet so the font fetch starts immediately
     instead of waiting for geist.css to parse; otherwise an installed app shows
     a flash of fallback text on every cold start. crossorigin is required on
     font preloads even same-origin, because font fetches are always CORS-mode. -->
<link rel="preload" as="font" type="font/woff2" crossorigin
      href="/design-system/fonts/geist-sans/Geist-Variable.woff2" />
<link rel="preload" as="font" type="font/woff2" crossorigin
      href="/design-system/fonts/geist-mono/GeistMono-Variable.woff2" />

<link rel="stylesheet" href="/design-system/geist.css" />
<link rel="stylesheet" href="/design-system/pwa/pwa.css" />

<link rel="manifest" href="/design-system/pwa/manifest.webmanifest" />
<link rel="icon" href="/design-system/pwa/icons/icon.svg" type="image/svg+xml" />
<link rel="apple-touch-icon" href="/design-system/pwa/icons/apple-touch-icon.png" />

<!-- Deferred by virtue of being a module, so it runs after the stylesheets —
     which it needs, since it reads the resolved --ds-background-100 back out of
     the DOM rather than duplicating the hex. -->
<script type="module" src="/design-system/pwa/theme.js"></script>
`,
);

console.log(
  `pwa: colors.json, manifest.webmanifest, head.html written (theme ${themeLight} / ${themeDark})`,
);
