import { readFileSync, writeFileSync } from "node:fs";

const SRC = "/home/user/V15C/design-system/tokens/theme.css";
const OUT_DIR = "/home/user/V15C/design-system/tokens";
const css = readFileSync(SRC, "utf8");

/** Grab the body of the first top-level `selector { ... }` block that declares --ds-*. */
function block(selector) {
  const re = new RegExp(`^${selector.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}\\s*\\{`, "m");
  const m = re.exec(css);
  if (!m) throw new Error(`no block for ${selector}`);
  let depth = 0;
  let i = m.index + m[0].length - 1;
  const start = i + 1;
  for (; i < css.length; i++) {
    if (css[i] === "{") depth++;
    else if (css[i] === "}") {
      depth--;
      if (depth === 0) return css.slice(start, i);
    }
  }
  throw new Error(`unterminated block for ${selector}`);
}

const light = block(":root");
const dark = block(".dark");

if (!light.includes("--ds-gray-100:")) throw new Error("light block missing --ds tokens");
if (!dark.includes("--ds-gray-100:")) throw new Error("dark block missing --ds tokens");

// ---- ds-tokens.css : framework-free literals -------------------------------
const header = `/* Geist design tokens — literal --ds-* custom properties.
 *
 * Extracted verbatim from @vercel/geistdocs@1.19.5 theme.css (Apache-2.0).
 * These are the same values that paint vercel.com.
 *
 * No Tailwind, no build step: import this file and the tokens are available.
 * Light values live on :root, dark values on .dark — toggle the class on <html>.
 *
 * Generated by design-system/scripts/extract-tokens.mjs — do not edit by hand.
 */
`;

writeFileSync(
  `${OUT_DIR}/ds-tokens.css`,
  `${header}\n:root {${light}}\n\n.dark {${dark}}\n`,
);

// ---- dark-auto.css : opt-in OS-preference mapping --------------------------
writeFileSync(
  `${OUT_DIR}/dark-auto.css`,
  `/* Optional: follow the OS colour scheme when no explicit class is set.
 *
 * Vercel's own theming is class-based (.dark on <html>). Import this file
 * *after* ds-tokens.css to additionally honour prefers-color-scheme, while
 * still letting an explicit .light / .dark class win.
 *
 * Generated by design-system/scripts/extract-tokens.mjs — do not edit by hand.
 */

@media (prefers-color-scheme: dark) {
  :root:not(.light) {${dark}}
}
`,
);

// ---- tokens.json : machine-readable ---------------------------------------
function parse(body) {
  const out = {};
  // Declarations may span several lines (shadows). Split on ';' at depth 0.
  for (const decl of body.split(";")) {
    const t = decl.trim();
    if (!t.startsWith("--")) continue;
    const idx = t.indexOf(":");
    if (idx === -1) continue;
    out[t.slice(0, idx).trim()] = t.slice(idx + 1).replace(/\s+/g, " ").trim();
  }
  return out;
}

const lightTokens = parse(light);
const darkTokens = parse(dark);

const group = (name) => {
  if (name.startsWith("--ds-shadow-") || name === "--ds-focus-ring") return "shadow";
  if (/^--ds-(gray-alpha|gray|blue|red|amber|green|teal|purple|pink)-\d+$/.test(name)) return "color";
  if (["--ds-black", "--ds-white", "--ds-background-100", "--ds-background-200"].includes(name)) return "color";
  return "other";
};

const names = [...new Set([...Object.keys(lightTokens), ...Object.keys(darkTokens)])];
const tokens = {};
for (const n of names) {
  tokens[n] = {
    group: group(n),
    light: lightTokens[n] ?? null,
    // Dark mode only redefines a subset; the rest inherit the light value.
    dark: darkTokens[n] ?? lightTokens[n] ?? null,
    darkOverridden: n in darkTokens,
  };
}

writeFileSync(
  `${OUT_DIR}/tokens.json`,
  `${JSON.stringify(
    {
      name: "Geist design tokens",
      source: {
        package: "@vercel/geistdocs",
        version: "1.19.5",
        file: "theme.css",
        license: "Apache-2.0",
      },
      note: "Values are verbatim from the upstream package. `dark` falls back to the light value when the .dark block does not override it; `darkOverridden` records which is which.",
      count: names.length,
      tokens,
    },
    null,
    2,
  )}\n`,
);

console.log(
  `light=${Object.keys(lightTokens).length} dark=${Object.keys(darkTokens).length} union=${names.length}`,
);
